version: '2'

services:
  odoo:
    build: ./odoo/
    command: odoo.py --load=web,web_kanban,session_redis,attachment_s3,logging_json
    volumes:
      - "data-odoo:/data/odoo"
    depends_on:
      - db
    environment:
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoodb
      - ADMIN_PASSWD=mijaebohb8Thae1g
      - RUNNING_ENV=dev

  db:
    image: camptocamp/postgresql:pg9.5-latest
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PG_SYSTEM_SHARED_BUFFERS=256MB
      - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
      - PG_SYSTEM_WAL_BUFFERS=8MB
      - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
    volumes:
      - "data-db:/var/lib/postgresql/data"

  nginx:
    image: camptocamp/odoo-nginx:11.0-1.2.1
    depends_on:
      - odoo

volumes:
  data-odoo:
  data-db:
