odoo:
  image: camptocamp/swisslux_odoo:9.4.3
  command: odoo --load=web,web_kanban,logging_json
  external_links:
    - postgres-cluster/lb:db
    - redis/redis:redis
  environment:
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - DB_PORT=${DB_PORT}
    - ADMIN_PASSWD=${ADMIN_PASSWD}
    - RUNNING_ENV=${RUNNING_ENV}
    - DEMO=${DEMO}
    - WORKERS=${WORKERS}
    - MAX_CRON_THREADS=${MAX_CRON_THREADS}
    - LOG_LEVEL=${LOG_LEVEL}
    - LOG_HANDLER=${LOG_HANDLER}
    - DB_MAXCONN=${DB_MAXCONN}
    - LIMIT_MEMORY_SOFT=${LIMIT_MEMORY_SOFT}
    - LIMIT_MEMORY_HARD=${LIMIT_MEMORY_HARD}
    - LIMIT_REQUEST=${LIMIT_REQUEST}
    - LIMIT_TIME_CPU=${LIMIT_TIME_CPU}
    - LIMIT_TIME_REAL=${LIMIT_TIME_REAL}
    - MARABUNTA_ALLOW_SERIE=False
    - MARABUNTA_MODE=${MARABUNTA_MODE}
    - AWS_HOST=${AWS_HOST}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_BUCKETNAME=${AWS_BUCKETNAME}
    - ODOO_SESSION_REDIS=${ODOO_SESSION_REDIS}
    - ODOO_SESSION_REDIS_HOST=${ODOO_SESSION_REDIS_HOST}
    - ODOO_SESSION_REDIS_PREFIX=${ODOO_SESSION_REDIS_PREFIX}
    - ODOO_CLOUD_PLATFORM_UNSAFE=${ODOO_CLOUD_PLATFORM_UNSAFE}
    - ODOO_LOGGING_JSON=${ODOO_LOGGING_JSON}
    - ODOO_STATSD=${ODOO_STATSD}
    - STATSD_CUSTOMER=swisslux
    - STATSD_ENVIRONMENT=${STATSD_ENVIRONMENT}
    - STATSD_HOST=${STATSD_HOST}
    - STATSD_PORT=${STATSD_PORT}
  labels:
    io.rancher.scheduler.affinity:host_label: application=true

nginx:
  image: camptocamp/odoo-nginx:9.0
  links:
    - odoo:odoo
  labels:
    io.rancher.scheduler.affinity:host_label: application=true
